name: build
on: [push, pull_request]

jobs:
  build_latex_pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make

      - name: create pdf artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: main.pdf